---
excludes:
  scopes:
    - pattern: "dev"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
    - pattern: "experiments"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for experimentation only."
resolutions:
  rule_violations:
    - message: ".*PyPI::fastapi:0\\.121\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/fastapi/fastapi/blob/master/LICENSE"
    - message: ".*PyPI::zipp:3\\.23\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/jaraco/zipp/blob/157860e9d6a793787d22a3ba5ac238799065b9b7/pyproject.toml#L24"
    - message: ".*PyPI::httpcore:1\\.0\\.9.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/encode/httpcore/blob/master/LICENSE.md"
    - message: ".*PyPI::starlette:0\\.49\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/Kludex/starlette/blob/main/LICENSE.md"
    - message: ".*PyPI::attrs:25\\.4\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-attrs/attrs/blob/main/LICENSE"
    - message: ".*PyPI::urllib3:2\\.6\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/urllib3/urllib3/blob/2.5.0/LICENSE.txt"
    - message: ".*PyPI::typing-inspection:0\\.4\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/typing-inspection/blob/main/LICENSE"
    - message: ".*PyPI::pydantic-core:2\\.41\\.5.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/pydantic-core/blob/main/LICENSE"
    - message: ".*PyPI::pydantic:2\\.12\\.4.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/pydantic/blob/main/LICENSE"
    - message: ".*PyPI::click:8\\.3\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pallets/click/blob/main/LICENSE.txt"
    - message: ".*PyPI::pandas:2\\.3\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pandas-dev/pandas/blob/main/LICENSE"
    - message: ".*PyPI::numpy:2\\.3\\.5.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/numpy/numpy/blob/main/LICENSE.txt"
    - message: ".*PyPI::typing-extensions:4\\.15\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Same as CPython: https://github.com/python/typing_extensions/blob/4.14.0/LICENSE"
    - message: ".*PyPI::jsonschema-specifications:2025\\.9\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-jsonschema/jsonschema-specifications/blob/main/COPYING"
    - message: ".*PyPI::opentelemetry-api:1\\.38\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-sdk:1\\.38\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-semantic-conventions:0\\.59b0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-exporter-otlp-proto-common:1\\.38\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-exporter-prometheus:0\\.59b0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-exporter-otlp-proto-grpc:1\\.38\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-proto:1\\.38\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::kaleido:1\\.2\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/plotly/Kaleido/blob/master/LICENSE"
    - message: ".*PyPI::rich-rst:1\\.3\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/wasi-master/rich-rst/blob/main/LICENSE"
    - message: ".*PyPI::secretstorage:3\\.4\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/mitya57/secretstorage/blob/master/LICENSE"
    - message: ".*PyPI::python-dotenv:1\\.2\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/theskumar/python-dotenv/blob/main/LICENSE"
    - message: ".*PyPI::anyio:4\\.11\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/agronholm/anyio/blob/master/LICENSE"
    - message: ".*PyPI::keyring:25\\.7\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://pypi.org/project/keyring/"
    - message: ".*PyPI::choreographer:1\\.2\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/plotly/choreographer/blob/main/LICENSE.md"
    - message: ".*PyPI::referencing:0\\.36\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-jsonschema/referencing?tab=MIT-1-ov-file"
    - message: ".*PyPI::jsonschema:4\\.25\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-jsonschema/jsonschema"
    - message: ".*PyPI::sse-starlette:3\\.0\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/sysid/sse-starlette/blob/main/LICENSE"
    - message: ".*PyPI::pytest-xdist:3\\.8\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pytest-dev/pytest-xdist/blob/master/LICENSE"
    - message: ".*PyPI::logistro:2\\.0\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/geopozo/logistro/blob/main/LICENSE"
    - message: ".*PyPI::cffi:2\\.0\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-cffi/cffi/blob/main/LICENSE"
    - message: ".*PyPI::cryptography:46\\.0\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0 and BSD-3 License: https://github.com/pyca/cryptography/?tab=Apache-2.0-2-ov-file and https://github.com/pyca/cryptography/?tab=BSD-3-Clause-3-ov-file"
    - message: ".*PyPI::jeepney:0\\.9\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://gitlab.com/takluyver/jeepney/-/blob/master/LICENSE"
    - message: ".*PyPI::more-itertools:10\\.8\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/more-itertools/more-itertools/blob/master/LICENSE"
    - message: ".*PyPI::rpds-py:0\\.29\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/crate-py/rpds/blob/main/LICENSE"
    - message: ".*PyPI::idna:3\\.11.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/kjd/idna/blob/master/LICENSE.md"
    - message: ".*PyPI::jaraco-functools:4\\.3\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://pypi.org/project/jaraco.functools/"
    - message: ".*PyPI::iniconfig:2\\.3\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pytest-dev/iniconfig/blob/main/LICENSE"
    - message: ".*PyPI::annotated-doc:0\\.0\\.4.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/fastapi/annotated-doc/blob/main/LICENSE"
    - message: ".*PyPI::uvicorn:0\\.38\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/Kludex/uvicorn/blob/main/LICENSE.md"
    - message: ".*PyPI::docutils:0\\.22\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD License, GPL, Public Domain: https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/LICENSE.txt"
    - message: ".*PyPI::pytest-timeout:2\\.4\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pytest-dev/pytest-timeout/blob/main/LICENSE"




