---
excludes:
  scopes:
    - pattern: "dev"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
    - pattern: "integration"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for integration testing only."
    - pattern: "experiments"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for experimentation only."
resolutions:
  rule_violations:
    - message: ".*PyPI::aidial-client:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/epam/ai-dial-client-python/blob/main/LICENSE"
    - message: ".*PyPI::fastapi:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/fastapi/fastapi/blob/master/LICENSE"
    - message: ".*PyPI::zipp:3\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/jaraco/zipp/blob/main/pyproject.toml#L24"
    - message: ".*PyPI::jaraco-context:6\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/jaraco/jaraco.context/blob/main/pyproject.toml#L24"
    - message: ".*PyPI::httpcore:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/encode/httpcore/blob/master/LICENSE.md"
    - message: ".*PyPI::starlette:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/Kludex/starlette/blob/main/LICENSE.md"
    - message: ".*PyPI::attrs:25\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-attrs/attrs/blob/main/LICENSE"
    - message: ".*PyPI::urllib3:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/urllib3/urllib3/blob/2.5.0/LICENSE.txt"
    - message: ".*PyPI::typing-inspection:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/typing-inspection/blob/main/LICENSE"
    - message: ".*PyPI::pydantic-core:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/pydantic-core/blob/main/LICENSE"
    - message: ".*PyPI::pydantic:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pydantic/pydantic/blob/main/LICENSE"
    - message: ".*PyPI::click:8\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pallets/click/blob/main/LICENSE.txt"
    - message: ".*PyPI::pandas:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pandas-dev/pandas/blob/main/LICENSE"
    - message: ".*PyPI::numpy:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/numpy/numpy/blob/main/LICENSE.txt"
    - message: ".*PyPI::typing-extensions:4\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Same as CPython: https://github.com/python/typing_extensions/blob/4.14.0/LICENSE"
    - message: ".*PyPI::jsonschema-specifications:2025\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-jsonschema/jsonschema-specifications/blob/main/COPYING"
    - message: ".*PyPI::opentelemetry-api:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-sdk:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-semantic-conventions:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-exporter-otlp-proto-common:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-exporter-prometheus:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-exporter-otlp-proto-grpc:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::opentelemetry-proto:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/open-telemetry/opentelemetry-python/blob/main/LICENSE"
    - message: ".*PyPI::rich-rst:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/wasi-master/rich-rst/blob/main/LICENSE"
    - message: ".*PyPI::secretstorage:3\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/mitya57/secretstorage/blob/master/LICENSE"
    - message: ".*PyPI::python-dotenv:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/theskumar/python-dotenv/blob/main/LICENSE"
    - message: ".*PyPI::anyio:4\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/agronholm/anyio/blob/master/LICENSE"
    - message: ".*PyPI::keyring:25\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://pypi.org/project/keyring/"
    - message: ".*PyPI::referencing:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-jsonschema/referencing?tab=MIT-1-ov-file"
    - message: ".*PyPI::jsonschema:4\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-jsonschema/jsonschema"
    - message: ".*PyPI::sse-starlette:3\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/sysid/sse-starlette/blob/main/LICENSE"
    - message: ".*PyPI::pytest:9\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pytest-dev/pytest/blob/main/LICENSE"
    - message: ".*PyPI::pytest-asyncio:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/pytest-dev/pytest-asyncio/blob/main/LICENSE"
    - message: ".*PyPI::pytest-xdist:3\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pytest-dev/pytest-xdist/blob/master/LICENSE"
    - message: ".*PyPI::logistro:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/geopozo/logistro/blob/main/LICENSE"
    - message: ".*PyPI::cffi:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/python-cffi/cffi/blob/main/LICENSE"
    - message: ".*PyPI::cryptography:46\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0 and BSD-3 License: https://github.com/pyca/cryptography/?tab=Apache-2.0-2-ov-file and https://github.com/pyca/cryptography/?tab=BSD-3-Clause-3-ov-file"
    - message: ".*PyPI::jeepney:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://gitlab.com/takluyver/jeepney/-/blob/master/LICENSE"
    - message: ".*PyPI::more-itertools:10\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/more-itertools/more-itertools/blob/master/LICENSE"
    - message: ".*PyPI::rpds-py:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/crate-py/rpds/blob/main/LICENSE"
    - message: ".*PyPI::idna:3\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/kjd/idna/blob/master/LICENSE.md"
    - message: ".*PyPI::jaraco-functools:4\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://pypi.org/project/jaraco.functools/"
    - message: ".*PyPI::iniconfig:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pytest-dev/iniconfig/blob/main/LICENSE"
    - message: ".*PyPI::annotated-doc:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/fastapi/annotated-doc/blob/main/LICENSE"
    - message: ".*PyPI::uvicorn:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/Kludex/uvicorn/blob/main/LICENSE.md"
    - message: ".*PyPI::docutils:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD License, GPL, Public Domain: https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/LICENSE.txt"
    - message: ".*PyPI::pytest-timeout:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pytest-dev/pytest-timeout/blob/main/LICENSE"
    - message: ".*PyPI::prometheus-client:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/prometheus/client_python/blob/master/LICENSE"
    - message: ".*PyPI::fakeredis:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/cunla/fakeredis-py/blob/master/LICENSE"
    - message: ".*PyPI::lupa:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/scoder/lupa/blob/master/LICENSE.txt"
    - message: ".*PyPI::typer:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/fastapi/typer/blob/master/LICENSE"
    - message: ".*PyPI::cachetools:6\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/tkem/cachetools/blob/master/LICENSE"
    - message: ".*PyPI::importlib-metadata:8\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/python/importlib_metadata/blob/main/pyproject.toml#L24"
    - message: ".*PyPI::python-json-logger:4\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/nhairs/python-json-logger/blob/main/LICENSE"
    - message: ".*PyPI::websockets:16\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/python-websockets/websockets/blob/main/LICENSE"
    - message: ".*PyPI::grpcio:1\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/grpc/grpc/blob/master/LICENSE"
    - message: ".*PyPI::cachetools:7\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/tkem/cachetools/blob/master/LICENSE"
    - message: ".*PyPI::packaging:26\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Dual (APL-2.0 & BSD-2): https://github.com/pypa/packaging/blob/main/LICENSE"
    - message: ".*PyPI::pyjwt:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/jpadilla/pyjwt/blob/master/LICENSE"
    - message: ".*PyPI::pycparser:3\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/eliben/pycparser/blob/main/LICENSE"
    - message: ".*PyPI::caio:0\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache License 2.0: https://github.com/mosquito/caio/blob/master/COPYING"
    - message: ".*PyPI::pygments:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD-2-Clause License: https://github.com/pygments/pygments/blob/master/LICENSE"

# WARNINGS
    - message: ".*PyPI::packaging:25\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Dual (APL-2.0 & BSD-2): https://github.com/pypa/packaging/blob/main/LICENSE"
    - message: ".*PyPI::python-dateutil:2\\..*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Dual (APL-2.0 and BSD-2): https://github.com/dateutil/dateutil/blob/master/LICENSE"
