name: PR Workflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_tests:
    uses: epam/ai-dial-ci/.github/workflows/python_docker_pr.yml@3.0.0
    secrets: inherit
    with:
      python-version: "3.13"
      poetry-version: "2.1.1"
      ort-enabled: false
      trivy-enabled: false
      code-checks-enabled: false
